name: AxBlockLimiter
version: '${project.version}'
main: hu.kxtsoo.axBlockLimiter.AxBlockLimiter
api-version: '1.20'
author: 'kxtsoo'

softdepend:
  - KingdomsX

libraries:
  - dev.dejvokep:boosted-yaml:1.3
  - com.zaxxer:HikariCP:5.1.0
  - com.h2database:h2:2.1.214